apiVersion: v1
kind: Pod 
metadata:
  name: np-pod
  labels:
    app: test
spec:
  containers:
    - name: test-con-2
      image: nginx:1.29
      ports:
        - containerPort: 80
          protocol: TCP