apiVersion: v1
kind: Pod 
metadata:
  name: lbpod
  labels:
    app: dummypod
spec:
  containers:
    - name: my-container
      image: nginx:1.29    
      ports:
        - containerPort: 80
          protocol: TCP