apiVersion: v1
kind: Pod 
metadata:
  name: lb-pod
  labels:
    app: myapp
spec:
  containers:
    - name: pythoncontainer
      image: mudasir102/python-repo:my-python
      ports:
        - containerPort: 5001
          protocol: TCP