apiVersion: v1
kind: Pod 
metadata:
  name: service-pod-1
  labels:
    app: test
spec:
  containers:
    - name: test-container-2
      image: jenkins/jenkins:jdk21
      ports:
        - containerPort: 8080
          protocol: TCP