apiVersion: v1
kind: Pod 
metadata:
  name: svcpod
  labels:
    app: dummy
spec:
  containers:
    - name: javacontainer
      image: mudasir102/java-repo:my-java
      ports:
        - containerPort: 8080
          protocol: TCP