apiVersion: v1
kind: Pod 
metadata:
  name: svc-pod-1
  labels:
    app: dummy
spec:
  containers:
    - name: java-container
      image: mudasir102/java-repo:my-java
      ports:
        - containerPort: 8080
          protocol: TCP