apiVersion: v1
kind: Pod 
metadata:
  name: cip-pod
  labels:
    app: test
spec:
  containers:
    - name: test-container-1
      image: nginx:1.29
      ports:
        - containerPort: 80
          protocol: TCP