apiVersion: v1
kind: Pod 
metadata:
  name: service-pod
  labels:
    app: test
spec:
  containers:
    - name: test-con-1
      image: jenkins/jenkins:jdk21
      ports:
        - containerPort: 8080
          protocol: TCP