apiVersion: v1
kind: Pod
metadata: 
  name: en-pod
  labels:
    app: test-2
spec:
  containers:
    - name: container0
      image: nginx:1.29
      ports:
        - containerPort: 80
          protocol: TCP